# First Example
## No hidden layer ANN

In [19]:
import numpy as np

#sigmoid function
def nonlin(x,deriv = False):
    if (deriv == True):
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

In [20]:
# input dataset
X = np.array([
        [0,0,1],
        [0,1,1],
        [1,0,1],
        [1,1,1]
             ])

# output dataset
y = np.array([[0,0,1,1]]).T

In [25]:
# seed random number to start calculation
# deterministic
np.random.seed(1030)

# initialize weights randomly with mean 0
syn0 = 2 * np.random.random((3,1)) - 1

for iter in xrange(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    
    # how much did weight miss
    l1_error = y - l1
    
    # multiply how much weight missed by the slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    
    #update weights
    syn0 += np.dot(l0.T, l1_delta)
    
print 'Output After Training:'
print l1
    

Output After Training:
[[ 0.00966781]
 [ 0.00786381]
 [ 0.99359062]
 [ 0.99211763]]


# Second Example
## One hidden layer ANN

In [31]:
import numpy as np
def nonlin(x,deriv = False):
    if (deriv == True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [32]:
# input dataset
X = np.array([
        [0,0,1],
        [0,1,1],
        [1,0,1],
        [1,1,1]
             ])

# output dataset
y = np.array([[0,1,1,0]]).T

In [38]:
np.random.seed(1030)

# initialize weights randomly with mean 0
syn0 = 2 * np.random.random((3,4)) - 1
syn1 = 2 * np.random.random((4,1)) - 1

for j in xrange(60000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))    
    l2 = nonlin(np.dot(l1,syn1))
    
    # how much did weight miss
    l2_error = y - l2
    
    # show training progress
    if (j % 10000) == 0:
        print "Error:" + str(np.mean(np.abs(l2_error)))
        
    l2_delta = l2_error * nonlin(l2,True)
    
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta = l1_error * nonlin(l1,True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
    
print 'Output After Training:'
print l2    

Error:0.500722751734
Error:0.00944423263148
Error:0.00645451300598
Error:0.00520328533237
Error:0.00447524466286
Error:0.00398526960138
Output After Training:
[[ 0.00377867]
 [ 0.99607282]
 [ 0.99642215]
 [ 0.00322397]]


# Tuning the Alpha

In [39]:
import numpy as np
def nonlin(x,deriv = False):
    if (deriv == True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [40]:
# input dataset
X = np.array([
        [0,0,1],
        [0,1,1],
        [1,0,1],
        [1,1,1]
             ])

# output dataset

y = np.array([[0,1,1,0]]).T

In [42]:
alphas = [0.001,0.01,0.1,1,10,100,1000]


for alpha in alphas:
    print "\nTraining With Alpha:"+str(alpha)
    
    np.random.seed(1030)

    # initialize weights randomly with mean 0
    syn0 = 2 * np.random.random((3,4)) - 1
    syn1 = 2 * np.random.random((4,1)) - 1

    for j in xrange(60000):
        # forward propagation
        l0 = X
        l1 = nonlin(np.dot(l0,syn0))    
        l2 = nonlin(np.dot(l1,syn1))

        # how much did weight miss
        l2_error = y - l2

        # show training progress
        if (j % 10000) == 0:
            print "Error after "+str(j) +" iteratios:" + str(np.mean(np.abs(l2_error)))

        l2_delta = l2_error * nonlin(l2,True)

        l1_error = l2_delta.dot(syn1.T)

        l1_delta = l1_error * nonlin(l1,True)

        syn1 += alpha*(l1.T.dot(l2_delta))
        syn0 += alpha*(l0.T.dot(l1_delta))


    print 'Output After Training:'
    print l2    


Training With Alpha:0.001
Error after 0 iteratios:0.500722751734
Error after 10000 iteratios:0.500541492509
Error after 20000 iteratios:0.500383825972
Error after 30000 iteratios:0.500255238651
Error after 40000 iteratios:0.500144928598
Error after 50000 iteratios:0.500044559456
Output After Training:
[[ 0.51801399]
 [ 0.48130721]
 [ 0.52450394]
 [ 0.48758856]]

Training With Alpha:0.01
Error after 0 iteratios:0.500722751734
Error after 10000 iteratios:0.499495969632
Error after 20000 iteratios:0.493923014575
Error after 30000 iteratios:0.423222529413
Error after 40000 iteratios:0.215490950025
Error after 50000 iteratios:0.124592080743
Output After Training:
[[ 0.08588755]
 [ 0.91131955]
 [ 0.89339436]
 [ 0.08130021]]

Training With Alpha:0.1
Error after 0 iteratios:0.500722751734
Error after 10000 iteratios:0.0482125985408
Error after 20000 iteratios:0.0263339106834
Error after 30000 iteratios:0.0197018971925
Error after 40000 iteratios:0.0163078069019
Error after 50000 iteratios:0.0